1) Given the array split the array at the middle (if it is odd length consider next higher integer), add reverse the array.

Ex:
if input is [12,10,5,6,52,36] 
output should be [6,52,36,12,10,5]

if input is  [12,10,5,6,52,36,34]
output should be [6,52,36,34,12,10,5]

In [1]:
import math
import numpy as np
# Complete this function to get the desired result

def reverseatCenter(arr):
    ################## the idea is to get the index of center followed by which we can index the numpy array
    ################## and concatenate according to our needs
    center = int(np.floor(arr.shape[0]/2))
    arr2 = np.concatenate([arr[center:] , arr[:center]])
    return arr2

In [2]:
# Print wroking examples
list_arr = []
list_arr.append(np.array([12,10,5,6,52,36]))
list_arr.append(np.array([12,10,5,6,52,36,34]))
list_arr.append(np.array([-10,0,1,67,84,543,34,25,6,8,32]))
list_arr.append(np.array([i for i in range(20)]))

for arr in list_arr :
    print('Actual Array : ',arr)
    print('Reversed Array at center : ',reverseatCenter(arr))
    print('\n--------------------------------\n')

Actual Array :  [12 10  5  6 52 36]
Reversed Array at center :  [ 6 52 36 12 10  5]

--------------------------------

Actual Array :  [12 10  5  6 52 36 34]
Reversed Array at center :  [ 6 52 36 34 12 10  5]

--------------------------------

Actual Array :  [-10   0   1  67  84 543  34  25   6   8  32]
Reversed Array at center :  [543  34  25   6   8  32 -10   0   1  67  84]

--------------------------------

Actual Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reversed Array at center :  [10 11 12 13 14 15 16 17 18 19  0  1  2  3  4  5  6  7  8  9]

--------------------------------



2) Given a list of numbers, return a list where all adjacent duplicate elements have been removed.

Ex:

2, 2, 2, 3, 2 returns 2, 3, 2.

In [3]:
# Complete the function to get the desired result
import numpy as np

########## the method is to create another array which is composed of numbers which do not repeat
########## this is taken care using the temp variable which notes the previously occuring number
def remove_adjacent(b):
    temp = b[0]
    arr_refined = [temp]
    for i in range(b.shape[0]) :
        if b[i] == temp : 
            continue
        arr_refined.append(b[i])
        temp = b[i]
    return np.array(arr_refined)

In [6]:
# Print working examples
list_arr = []
list_arr.append(np.array([2,2,2,3,2]))
list_arr.append(np.array([12,10,5,6,52,36,34,34,34,34,34]))
list_arr.append(np.array([-10,-10,-10,0,1,67,84]))
list_arr.append(np.array([-10,-10,-10,0,1,67,67,67,67,67,85,85,67,67,84,1,1,1,1,1,1,1]))
list_arr.append(np.array([i for i in range(20)]))

for arr in list_arr :
    print('Actual Array : ',arr)
    print('Array with no consecutive number same : ',remove_adjacent(arr))
    print('\n--------------------------------\n')

Actual Array :  [2 2 2 3 2]
Array with no consecutive number same :  [2 3 2]

--------------------------------

Actual Array :  [12 10  5  6 52 36 34 34 34 34 34]
Array with no consecutive number same :  [12 10  5  6 52 36 34]

--------------------------------

Actual Array :  [-10 -10 -10   0   1  67  84]
Array with no consecutive number same :  [-10   0   1  67  84]

--------------------------------

Actual Array :  [-10 -10 -10   0   1  67  67  67  67  67  85  85  67  67  84   1   1   1
   1   1   1   1]
Array with no consecutive number same :  [-10   0   1  67  85  67  84   1]

--------------------------------

Actual Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array with no consecutive number same :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

--------------------------------



3) given matrix of 7x7 full of ones, create a square with given side length (center same as original square(7x7)) replace ones with zeors at the edges for example,



$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$
After modification
$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 0 & 1 & 0 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$

In [36]:
import numpy as np
# write programm to get the desired result
def transform(mat_2d , side_length) :
    center = (int(np.ceil((mat_2d.shape[0]-1)/2)),int(np.ceil((mat_2d.shape[1]-1)/2)))
    transformed_mat_2d = mat_2d.copy()
    transformed_mat_2d[center[0]-int(np.floor(side_length/2)):center[0]+int(np.ceil(side_length/2)),center[1]-int(np.floor(side_length/2))] = 0
    transformed_mat_2d[center[0]-int(np.floor(side_length/2)):center[0]+int(np.ceil(side_length/2)),center[1]+int(np.floor(side_length/2))] = 0
    transformed_mat_2d[center[0]-int(np.floor(side_length/2)),center[0]-int(np.floor(side_length/2)):center[1]+int(np.ceil(side_length/2))] = 0
    transformed_mat_2d[center[0]+int(np.floor(side_length/2)),center[0]-int(np.floor(side_length/2)):center[1]+int(np.ceil(side_length/2))] = 0
    return transformed_mat_2d 

In [37]:
#Print working examples
k = 7 ######### length of the 2D array
mat_2d = np.ones((k,k))
side_length = [i for i in range(3,k+1) if i%2==1] ####### the various possible inner squares we can draw on the matrix
for i in side_length :
    print('The inner square with side length : ',i)
    print(transform(mat_2d,i))
    print('\n-----------------------------------------\n')

The inner square with side length :  3
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

-----------------------------------------

The inner square with side length :  5
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

-----------------------------------------

The inner square with side length :  7
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

-----------------------------------------



4) Paragraph present in data.txt is encoded such that each alphabet in word is incremented to next ascii value. Decode the paragraph present in the data_encoded.txt (Hint: decrease the ascii value of each character in the word)


In [7]:
def sentence_decode(str):
    # write the code here
    dec_words = ''
    
    for i in str : 
########## We need to make sure that the spaces are left as such so that the decode is proper
########## ascii value of ' ' is 32
        if ord(i) != 32  : 
            dec_words = dec_words + chr(ord(i) - 1)
        else : 
            dec_words = dec_words + i
    return dec_words

In [8]:
with open ("data_encoded.txt", "r") as myfile:
    data=myfile.read()
    print(data)
    print(" ")
    print(sentence_decode(data))
decoded_text = sentence_decode(data)

ebub bobmztjt jt b qspdftt pg jotqfdujoh- dmfbotjoh- usbotgpsnjoh boe npefmjoh ebub xjui uif hpbm pg ejtdpwfsjoh vtfgvm jogpsnbujpo- jogpsnjoh dpodmvtjpot boe tvqqpsujoh efdjtjpo.nbljoh/ ebub bobmztjt ibt nvmujqmf gbdfut boe bqqspbdift- fodpnqbttjoh ejwfstf ufdiojrvft voefs b wbsjfuz pg obnft- boe jt vtfe jo ejggfsfou cvtjoftt- tdjfodf- boe tpdjbm tdjfodf epnbjot/ jo upebz(t cvtjoftt xpsme- ebub bobmztjt qmbzt b spmf jo nbljoh efdjtjpot npsf tdjfoujgjd boe ifmqjoh cvtjofttft pqfsbuf npsf fggfdujwfmz/
 
data analysis is a process of inspecting, cleansing, transforming and modeling data with the goal of discovering useful information, informing conclusions and supporting decision-making. data analysis has multiple facets and approaches, encompassing diverse techniques under a variety of names, and is used in different business, science, and social science domains. in today's business world, data analysis plays a role in making decisions more scientific and helping businesses operate more

In [9]:
# Has to print the decoded paragraph.
print(decoded_text)

data analysis is a process of inspecting, cleansing, transforming and modeling data with the goal of discovering useful information, informing conclusions and supporting decision-making. data analysis has multiple facets and approaches, encompassing diverse techniques under a variety of names, and is used in different business, science, and social science domains. in today's business world, data analysis plays a role in making decisions more scientific and helping businesses operate more effectively.
